### ISSUE TITLE
Setting up

### ISSUE THREAD

**Issue by notori0usss** [joynalam67598/inventory-management-system-with-pos#26]
How can I run this project?

**Comment by joynalam67598** [comment]
First clone the repo on your local. Then start local server(apache). Add **database credentials** in **.env** file (create .env file if not exist following .env.example). Then follow the process below:

1. Open terminal in api folder then run migration and seed command. if it's successfully done run `php artisan server`. Open the url with any browser.
2. Open terminal in app folder then run `npm start` or `yarn start`
